package com.otv.model;

// default package
// Generated Jun 4, 2013 7:53:45 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TActorAddress generated by hbm2java
 */
@Entity
@Table(name = "t_actor_address", schema = "public")
public class TActorAddress implements java.io.Serializable {

	private int acadId;
	private TAddress TAddress;
	private TActor TActor;
	private String acadUpdatedBy;
	private Date acadUpdatedOn;

	public TActorAddress() {
	}

	public TActorAddress(int acadId) {
		this.acadId = acadId;
	}

	public TActorAddress(int acadId, TAddress TAddress, TActor TActor,
			String acadUpdatedBy, Date acadUpdatedOn) {
		this.acadId = acadId;
		this.TAddress = TAddress;
		this.TActor = TActor;
		this.acadUpdatedBy = acadUpdatedBy;
		this.acadUpdatedOn = acadUpdatedOn;
	}

	@Id
	@Column(name = "acad_id", unique = true, nullable = false)
	public int getAcadId() {
		return this.acadId;
	}

	public void setAcadId(int acadId) {
		this.acadId = acadId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "acad_address_id")
	public TAddress getTAddress() {
		return this.TAddress;
	}

	public void setTAddress(TAddress TAddress) {
		this.TAddress = TAddress;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "acad_actor_id")
	public TActor getTActor() {
		return this.TActor;
	}

	public void setTActor(TActor TActor) {
		this.TActor = TActor;
	}

	@Column(name = "acad_updated_by", length = 200)
	public String getAcadUpdatedBy() {
		return this.acadUpdatedBy;
	}

	public void setAcadUpdatedBy(String acadUpdatedBy) {
		this.acadUpdatedBy = acadUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "acad_updated_on", length = 29)
	public Date getAcadUpdatedOn() {
		return this.acadUpdatedOn;
	}

	public void setAcadUpdatedOn(Date acadUpdatedOn) {
		this.acadUpdatedOn = acadUpdatedOn;
	}

}
