package com.otv.model;

// default package
// Generated Jun 4, 2013 7:53:45 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TCode generated by hbm2java
 */
@Entity
@Table(name = "t_code", schema = "public")
public class TCode implements java.io.Serializable {

	private int codeId;
	private TCodeType TCodeType;
	private String codeCode;
	private String codeShortDesc;
	private String codeLongDesc;
	private byte[] codeBitmap;
	private Integer codeSystemId;
	private String codeTags;
	private String codeUpdatedBy;
	private Date codeUpdatedOn;
	private Set<TAddress> TAddressesForAddrCityCodeId = new HashSet<TAddress>(0);
	private Set<TAddress> TAddressesForAddrStateCodeId = new HashSet<TAddress>(
			0);
	private Set<TProperty> TPropertiesForPrptLengthUnitCodeId = new HashSet<TProperty>(
			0);
	private Set<TCountry> TCountries = new HashSet<TCountry>(0);
	private Set<TProperty> TPropertiesForPrptThicknessUnitCodeId = new HashSet<TProperty>(
			0);
	private Set<TCity> TCities = new HashSet<TCity>(0);
	private Set<TPlacedOrder> TPlacedOrders = new HashSet<TPlacedOrder>(0);
	private Set<TState> TStates = new HashSet<TState>(0);
	private Set<TProperty> TPropertiesForPrptHeightUnitCodeId = new HashSet<TProperty>(
			0);
	private Set<TRcorRmatLink> TRcorRmatLinksForRcrmQuantityUnitCodeId = new HashSet<TRcorRmatLink>(
			0);
	private Set<TPlorRmatLink> TPlorRmatLinksForPlrmQuantityUnitCodeId = new HashSet<TPlorRmatLink>(
			0);
	private Set<TProperty> TPropertiesForPrptPrimaryColorCodeId = new HashSet<TProperty>(
			0);
	private Set<TProperty> TPropertiesForPrptWidthUnitCodeId = new HashSet<TProperty>(
			0);
	private Set<TAddress> TAddressesForAddrCountryCodeId = new HashSet<TAddress>(
			0);
	private Set<TPurchaseOrder> TPurchaseOrders = new HashSet<TPurchaseOrder>(0);
	private Set<TActor> TActors = new HashSet<TActor>(0);
	private Set<TAddress> TAddressesForAddrPhoneTypeCodeId = new HashSet<TAddress>(
			0);
	private Set<TReceivedOrder> TReceivedOrders = new HashSet<TReceivedOrder>(0);
	private Set<TRcorRmatLink> TRcorRmatLinksForRcrmWeightUnitCodeId = new HashSet<TRcorRmatLink>(
			0);
	private Set<TPlorRcorLink> TPlorRcorLinks = new HashSet<TPlorRcorLink>(0);
	private Set<TAddress> TAddressesForAddrTypeCodeId = new HashSet<TAddress>(0);
	private Set<TProduct> TProductsForProdTypeCodeId = new HashSet<TProduct>(0);
	private Set<TRawMaterial> TRawMaterials = new HashSet<TRawMaterial>(0);
	private Set<TProduct> TProductsForProdNameCodeId = new HashSet<TProduct>(0);
	private Set<TPlorRmatLink> TPlorRmatLinksForPlrmWeightUnitCodeId = new HashSet<TPlorRmatLink>(
			0);

	public TCode() {
	}

	public TCode(int codeId) {
		this.codeId = codeId;
	}

	public TCode(int codeId, TCodeType TCodeType, String codeCode,
			String codeShortDesc, String codeLongDesc, byte[] codeBitmap,
			Integer codeSystemId, String codeTags, String codeUpdatedBy,
			Date codeUpdatedOn, Set<TAddress> TAddressesForAddrCityCodeId,
			Set<TAddress> TAddressesForAddrStateCodeId,
			Set<TProperty> TPropertiesForPrptLengthUnitCodeId,
			Set<TCountry> TCountries,
			Set<TProperty> TPropertiesForPrptThicknessUnitCodeId,
			Set<TCity> TCities, Set<TPlacedOrder> TPlacedOrders,
			Set<TState> TStates,
			Set<TProperty> TPropertiesForPrptHeightUnitCodeId,
			Set<TRcorRmatLink> TRcorRmatLinksForRcrmQuantityUnitCodeId,
			Set<TPlorRmatLink> TPlorRmatLinksForPlrmQuantityUnitCodeId,
			Set<TProperty> TPropertiesForPrptPrimaryColorCodeId,
			Set<TProperty> TPropertiesForPrptWidthUnitCodeId,
			Set<TAddress> TAddressesForAddrCountryCodeId,
			Set<TPurchaseOrder> TPurchaseOrders, Set<TActor> TActors,
			Set<TAddress> TAddressesForAddrPhoneTypeCodeId,
			Set<TReceivedOrder> TReceivedOrders,
			Set<TRcorRmatLink> TRcorRmatLinksForRcrmWeightUnitCodeId,
			Set<TPlorRcorLink> TPlorRcorLinks,
			Set<TAddress> TAddressesForAddrTypeCodeId,
			Set<TProduct> TProductsForProdTypeCodeId,
			Set<TRawMaterial> TRawMaterials,
			Set<TProduct> TProductsForProdNameCodeId,
			Set<TPlorRmatLink> TPlorRmatLinksForPlrmWeightUnitCodeId) {
		this.codeId = codeId;
		this.TCodeType = TCodeType;
		this.codeCode = codeCode;
		this.codeShortDesc = codeShortDesc;
		this.codeLongDesc = codeLongDesc;
		this.codeBitmap = codeBitmap;
		this.codeSystemId = codeSystemId;
		this.codeTags = codeTags;
		this.codeUpdatedBy = codeUpdatedBy;
		this.codeUpdatedOn = codeUpdatedOn;
		this.TAddressesForAddrCityCodeId = TAddressesForAddrCityCodeId;
		this.TAddressesForAddrStateCodeId = TAddressesForAddrStateCodeId;
		this.TPropertiesForPrptLengthUnitCodeId = TPropertiesForPrptLengthUnitCodeId;
		this.TCountries = TCountries;
		this.TPropertiesForPrptThicknessUnitCodeId = TPropertiesForPrptThicknessUnitCodeId;
		this.TCities = TCities;
		this.TPlacedOrders = TPlacedOrders;
		this.TStates = TStates;
		this.TPropertiesForPrptHeightUnitCodeId = TPropertiesForPrptHeightUnitCodeId;
		this.TRcorRmatLinksForRcrmQuantityUnitCodeId = TRcorRmatLinksForRcrmQuantityUnitCodeId;
		this.TPlorRmatLinksForPlrmQuantityUnitCodeId = TPlorRmatLinksForPlrmQuantityUnitCodeId;
		this.TPropertiesForPrptPrimaryColorCodeId = TPropertiesForPrptPrimaryColorCodeId;
		this.TPropertiesForPrptWidthUnitCodeId = TPropertiesForPrptWidthUnitCodeId;
		this.TAddressesForAddrCountryCodeId = TAddressesForAddrCountryCodeId;
		this.TPurchaseOrders = TPurchaseOrders;
		this.TActors = TActors;
		this.TAddressesForAddrPhoneTypeCodeId = TAddressesForAddrPhoneTypeCodeId;
		this.TReceivedOrders = TReceivedOrders;
		this.TRcorRmatLinksForRcrmWeightUnitCodeId = TRcorRmatLinksForRcrmWeightUnitCodeId;
		this.TPlorRcorLinks = TPlorRcorLinks;
		this.TAddressesForAddrTypeCodeId = TAddressesForAddrTypeCodeId;
		this.TProductsForProdTypeCodeId = TProductsForProdTypeCodeId;
		this.TRawMaterials = TRawMaterials;
		this.TProductsForProdNameCodeId = TProductsForProdNameCodeId;
		this.TPlorRmatLinksForPlrmWeightUnitCodeId = TPlorRmatLinksForPlrmWeightUnitCodeId;
	}

	@Id
	@Column(name = "code_id", unique = true, nullable = false)
	public int getCodeId() {
		return this.codeId;
	}

	public void setCodeId(int codeId) {
		this.codeId = codeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "code_code_type_id")
	public TCodeType getTCodeType() {
		return this.TCodeType;
	}

	public void setTCodeType(TCodeType TCodeType) {
		this.TCodeType = TCodeType;
	}

	@Column(name = "code_code", length = 4)
	public String getCodeCode() {
		return this.codeCode;
	}

	public void setCodeCode(String codeCode) {
		this.codeCode = codeCode;
	}

	@Column(name = "code_short_desc", length = 100)
	public String getCodeShortDesc() {
		return this.codeShortDesc;
	}

	public void setCodeShortDesc(String codeShortDesc) {
		this.codeShortDesc = codeShortDesc;
	}

	@Column(name = "code_long_desc", length = 200)
	public String getCodeLongDesc() {
		return this.codeLongDesc;
	}

	public void setCodeLongDesc(String codeLongDesc) {
		this.codeLongDesc = codeLongDesc;
	}

	@Column(name = "code_bitmap")
	public byte[] getCodeBitmap() {
		return this.codeBitmap;
	}

	public void setCodeBitmap(byte[] codeBitmap) {
		this.codeBitmap = codeBitmap;
	}

	@Column(name = "code_system_id")
	public Integer getCodeSystemId() {
		return this.codeSystemId;
	}

	public void setCodeSystemId(Integer codeSystemId) {
		this.codeSystemId = codeSystemId;
	}

	@Column(name = "code_tags", length = 250)
	public String getCodeTags() {
		return this.codeTags;
	}

	public void setCodeTags(String codeTags) {
		this.codeTags = codeTags;
	}

	@Column(name = "code_updated_by", length = 200)
	public String getCodeUpdatedBy() {
		return this.codeUpdatedBy;
	}

	public void setCodeUpdatedBy(String codeUpdatedBy) {
		this.codeUpdatedBy = codeUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "code_updated_on", length = 29)
	public Date getCodeUpdatedOn() {
		return this.codeUpdatedOn;
	}

	public void setCodeUpdatedOn(Date codeUpdatedOn) {
		this.codeUpdatedOn = codeUpdatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCodeByAddrCityCodeId")
	public Set<TAddress> getTAddressesForAddrCityCodeId() {
		return this.TAddressesForAddrCityCodeId;
	}

	public void setTAddressesForAddrCityCodeId(
			Set<TAddress> TAddressesForAddrCityCodeId) {
		this.TAddressesForAddrCityCodeId = TAddressesForAddrCityCodeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCodeByAddrStateCodeId")
	public Set<TAddress> getTAddressesForAddrStateCodeId() {
		return this.TAddressesForAddrStateCodeId;
	}

	public void setTAddressesForAddrStateCodeId(
			Set<TAddress> TAddressesForAddrStateCodeId) {
		this.TAddressesForAddrStateCodeId = TAddressesForAddrStateCodeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCodeByPrptLengthUnitCodeId")
	public Set<TProperty> getTPropertiesForPrptLengthUnitCodeId() {
		return this.TPropertiesForPrptLengthUnitCodeId;
	}

	public void setTPropertiesForPrptLengthUnitCodeId(
			Set<TProperty> TPropertiesForPrptLengthUnitCodeId) {
		this.TPropertiesForPrptLengthUnitCodeId = TPropertiesForPrptLengthUnitCodeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCode")
	public Set<TCountry> getTCountries() {
		return this.TCountries;
	}

	public void setTCountries(Set<TCountry> TCountries) {
		this.TCountries = TCountries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCodeByPrptThicknessUnitCodeId")
	public Set<TProperty> getTPropertiesForPrptThicknessUnitCodeId() {
		return this.TPropertiesForPrptThicknessUnitCodeId;
	}

	public void setTPropertiesForPrptThicknessUnitCodeId(
			Set<TProperty> TPropertiesForPrptThicknessUnitCodeId) {
		this.TPropertiesForPrptThicknessUnitCodeId = TPropertiesForPrptThicknessUnitCodeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCode")
	public Set<TCity> getTCities() {
		return this.TCities;
	}

	public void setTCities(Set<TCity> TCities) {
		this.TCities = TCities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCode")
	public Set<TPlacedOrder> getTPlacedOrders() {
		return this.TPlacedOrders;
	}

	public void setTPlacedOrders(Set<TPlacedOrder> TPlacedOrders) {
		this.TPlacedOrders = TPlacedOrders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCode")
	public Set<TState> getTStates() {
		return this.TStates;
	}

	public void setTStates(Set<TState> TStates) {
		this.TStates = TStates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCodeByPrptHeightUnitCodeId")
	public Set<TProperty> getTPropertiesForPrptHeightUnitCodeId() {
		return this.TPropertiesForPrptHeightUnitCodeId;
	}

	public void setTPropertiesForPrptHeightUnitCodeId(
			Set<TProperty> TPropertiesForPrptHeightUnitCodeId) {
		this.TPropertiesForPrptHeightUnitCodeId = TPropertiesForPrptHeightUnitCodeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCodeByRcrmQuantityUnitCodeId")
	public Set<TRcorRmatLink> getTRcorRmatLinksForRcrmQuantityUnitCodeId() {
		return this.TRcorRmatLinksForRcrmQuantityUnitCodeId;
	}

	public void setTRcorRmatLinksForRcrmQuantityUnitCodeId(
			Set<TRcorRmatLink> TRcorRmatLinksForRcrmQuantityUnitCodeId) {
		this.TRcorRmatLinksForRcrmQuantityUnitCodeId = TRcorRmatLinksForRcrmQuantityUnitCodeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCodeByPlrmQuantityUnitCodeId")
	public Set<TPlorRmatLink> getTPlorRmatLinksForPlrmQuantityUnitCodeId() {
		return this.TPlorRmatLinksForPlrmQuantityUnitCodeId;
	}

	public void setTPlorRmatLinksForPlrmQuantityUnitCodeId(
			Set<TPlorRmatLink> TPlorRmatLinksForPlrmQuantityUnitCodeId) {
		this.TPlorRmatLinksForPlrmQuantityUnitCodeId = TPlorRmatLinksForPlrmQuantityUnitCodeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCodeByPrptPrimaryColorCodeId")
	public Set<TProperty> getTPropertiesForPrptPrimaryColorCodeId() {
		return this.TPropertiesForPrptPrimaryColorCodeId;
	}

	public void setTPropertiesForPrptPrimaryColorCodeId(
			Set<TProperty> TPropertiesForPrptPrimaryColorCodeId) {
		this.TPropertiesForPrptPrimaryColorCodeId = TPropertiesForPrptPrimaryColorCodeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCodeByPrptWidthUnitCodeId")
	public Set<TProperty> getTPropertiesForPrptWidthUnitCodeId() {
		return this.TPropertiesForPrptWidthUnitCodeId;
	}

	public void setTPropertiesForPrptWidthUnitCodeId(
			Set<TProperty> TPropertiesForPrptWidthUnitCodeId) {
		this.TPropertiesForPrptWidthUnitCodeId = TPropertiesForPrptWidthUnitCodeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCodeByAddrCountryCodeId")
	public Set<TAddress> getTAddressesForAddrCountryCodeId() {
		return this.TAddressesForAddrCountryCodeId;
	}

	public void setTAddressesForAddrCountryCodeId(
			Set<TAddress> TAddressesForAddrCountryCodeId) {
		this.TAddressesForAddrCountryCodeId = TAddressesForAddrCountryCodeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCode")
	public Set<TPurchaseOrder> getTPurchaseOrders() {
		return this.TPurchaseOrders;
	}

	public void setTPurchaseOrders(Set<TPurchaseOrder> TPurchaseOrders) {
		this.TPurchaseOrders = TPurchaseOrders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCode")
	public Set<TActor> getTActors() {
		return this.TActors;
	}

	public void setTActors(Set<TActor> TActors) {
		this.TActors = TActors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCodeByAddrPhoneTypeCodeId")
	public Set<TAddress> getTAddressesForAddrPhoneTypeCodeId() {
		return this.TAddressesForAddrPhoneTypeCodeId;
	}

	public void setTAddressesForAddrPhoneTypeCodeId(
			Set<TAddress> TAddressesForAddrPhoneTypeCodeId) {
		this.TAddressesForAddrPhoneTypeCodeId = TAddressesForAddrPhoneTypeCodeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCode")
	public Set<TReceivedOrder> getTReceivedOrders() {
		return this.TReceivedOrders;
	}

	public void setTReceivedOrders(Set<TReceivedOrder> TReceivedOrders) {
		this.TReceivedOrders = TReceivedOrders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCodeByRcrmWeightUnitCodeId")
	public Set<TRcorRmatLink> getTRcorRmatLinksForRcrmWeightUnitCodeId() {
		return this.TRcorRmatLinksForRcrmWeightUnitCodeId;
	}

	public void setTRcorRmatLinksForRcrmWeightUnitCodeId(
			Set<TRcorRmatLink> TRcorRmatLinksForRcrmWeightUnitCodeId) {
		this.TRcorRmatLinksForRcrmWeightUnitCodeId = TRcorRmatLinksForRcrmWeightUnitCodeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCode")
	public Set<TPlorRcorLink> getTPlorRcorLinks() {
		return this.TPlorRcorLinks;
	}

	public void setTPlorRcorLinks(Set<TPlorRcorLink> TPlorRcorLinks) {
		this.TPlorRcorLinks = TPlorRcorLinks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCodeByAddrTypeCodeId")
	public Set<TAddress> getTAddressesForAddrTypeCodeId() {
		return this.TAddressesForAddrTypeCodeId;
	}

	public void setTAddressesForAddrTypeCodeId(
			Set<TAddress> TAddressesForAddrTypeCodeId) {
		this.TAddressesForAddrTypeCodeId = TAddressesForAddrTypeCodeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCodeByProdTypeCodeId")
	public Set<TProduct> getTProductsForProdTypeCodeId() {
		return this.TProductsForProdTypeCodeId;
	}

	public void setTProductsForProdTypeCodeId(
			Set<TProduct> TProductsForProdTypeCodeId) {
		this.TProductsForProdTypeCodeId = TProductsForProdTypeCodeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCode")
	public Set<TRawMaterial> getTRawMaterials() {
		return this.TRawMaterials;
	}

	public void setTRawMaterials(Set<TRawMaterial> TRawMaterials) {
		this.TRawMaterials = TRawMaterials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCodeByProdNameCodeId")
	public Set<TProduct> getTProductsForProdNameCodeId() {
		return this.TProductsForProdNameCodeId;
	}

	public void setTProductsForProdNameCodeId(
			Set<TProduct> TProductsForProdNameCodeId) {
		this.TProductsForProdNameCodeId = TProductsForProdNameCodeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCodeByPlrmWeightUnitCodeId")
	public Set<TPlorRmatLink> getTPlorRmatLinksForPlrmWeightUnitCodeId() {
		return this.TPlorRmatLinksForPlrmWeightUnitCodeId;
	}

	public void setTPlorRmatLinksForPlrmWeightUnitCodeId(
			Set<TPlorRmatLink> TPlorRmatLinksForPlrmWeightUnitCodeId) {
		this.TPlorRmatLinksForPlrmWeightUnitCodeId = TPlorRmatLinksForPlrmWeightUnitCodeId;
	}

}
