package com.otv.model;

// default package
// Generated Jun 4, 2013 7:53:45 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TCodeType generated by hbm2java
 */
@Entity
@Table(name = "t_code_type", schema = "public")
public class TCodeType implements java.io.Serializable {

	private int cdtyId;
	private String cdtyCode;
	private String cdtyShortDesc;
	private String cdtyLongDesc;
	private byte[] cdtyBitmap;
	private Integer cdtySystemId;
	private String cdtyTags;
	private String cdtyUpdatedBy;
	private Date cdtyUpdatedOn;
	private Set<TCode> TCodes = new HashSet<TCode>(0);

	public TCodeType() {
	}

	public TCodeType(int cdtyId) {
		this.cdtyId = cdtyId;
	}

	public TCodeType(int cdtyId, String cdtyCode, String cdtyShortDesc,
			String cdtyLongDesc, byte[] cdtyBitmap, Integer cdtySystemId,
			String cdtyTags, String cdtyUpdatedBy, Date cdtyUpdatedOn,
			Set<TCode> TCodes) {
		this.cdtyId = cdtyId;
		this.cdtyCode = cdtyCode;
		this.cdtyShortDesc = cdtyShortDesc;
		this.cdtyLongDesc = cdtyLongDesc;
		this.cdtyBitmap = cdtyBitmap;
		this.cdtySystemId = cdtySystemId;
		this.cdtyTags = cdtyTags;
		this.cdtyUpdatedBy = cdtyUpdatedBy;
		this.cdtyUpdatedOn = cdtyUpdatedOn;
		this.TCodes = TCodes;
	}

	@Id
	@Column(name = "cdty_id", unique = true, nullable = false)
	public int getCdtyId() {
		return this.cdtyId;
	}

	public void setCdtyId(int cdtyId) {
		this.cdtyId = cdtyId;
	}

	@Column(name = "cdty_code", length = 4)
	public String getCdtyCode() {
		return this.cdtyCode;
	}

	public void setCdtyCode(String cdtyCode) {
		this.cdtyCode = cdtyCode;
	}

	@Column(name = "cdty_short_desc", length = 100)
	public String getCdtyShortDesc() {
		return this.cdtyShortDesc;
	}

	public void setCdtyShortDesc(String cdtyShortDesc) {
		this.cdtyShortDesc = cdtyShortDesc;
	}

	@Column(name = "cdty_long_desc", length = 200)
	public String getCdtyLongDesc() {
		return this.cdtyLongDesc;
	}

	public void setCdtyLongDesc(String cdtyLongDesc) {
		this.cdtyLongDesc = cdtyLongDesc;
	}

	@Column(name = "cdty_bitmap")
	public byte[] getCdtyBitmap() {
		return this.cdtyBitmap;
	}

	public void setCdtyBitmap(byte[] cdtyBitmap) {
		this.cdtyBitmap = cdtyBitmap;
	}

	@Column(name = "cdty_system_id")
	public Integer getCdtySystemId() {
		return this.cdtySystemId;
	}

	public void setCdtySystemId(Integer cdtySystemId) {
		this.cdtySystemId = cdtySystemId;
	}

	@Column(name = "cdty_tags", length = 250)
	public String getCdtyTags() {
		return this.cdtyTags;
	}

	public void setCdtyTags(String cdtyTags) {
		this.cdtyTags = cdtyTags;
	}

	@Column(name = "cdty_updated_by", length = 200)
	public String getCdtyUpdatedBy() {
		return this.cdtyUpdatedBy;
	}

	public void setCdtyUpdatedBy(String cdtyUpdatedBy) {
		this.cdtyUpdatedBy = cdtyUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cdty_updated_on", length = 29)
	public Date getCdtyUpdatedOn() {
		return this.cdtyUpdatedOn;
	}

	public void setCdtyUpdatedOn(Date cdtyUpdatedOn) {
		this.cdtyUpdatedOn = cdtyUpdatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCodeType")
	public Set<TCode> getTCodes() {
		return this.TCodes;
	}

	public void setTCodes(Set<TCode> TCodes) {
		this.TCodes = TCodes;
	}

}
