package com.otv.model;

// default package
// Generated Jun 4, 2013 7:53:45 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TCountry generated by hbm2java
 */
@Entity
@Table(name = "t_country", schema = "public")
public class TCountry implements java.io.Serializable {

	private int ctryId;
	private TCode TCode;
	private String ctryUpdatedBy;
	private Date ctryUpdatedOn;
	private Set<TState> TStates = new HashSet<TState>(0);

	public TCountry() {
	}

	public TCountry(int ctryId) {
		this.ctryId = ctryId;
	}

	public TCountry(int ctryId, TCode TCode, String ctryUpdatedBy,
			Date ctryUpdatedOn, Set<TState> TStates) {
		this.ctryId = ctryId;
		this.TCode = TCode;
		this.ctryUpdatedBy = ctryUpdatedBy;
		this.ctryUpdatedOn = ctryUpdatedOn;
		this.TStates = TStates;
	}

	@Id
	@Column(name = "ctry_id", unique = true, nullable = false)
	public int getCtryId() {
		return this.ctryId;
	}

	public void setCtryId(int ctryId) {
		this.ctryId = ctryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ctry_code_id")
	public TCode getTCode() {
		return this.TCode;
	}

	public void setTCode(TCode TCode) {
		this.TCode = TCode;
	}

	@Column(name = "ctry_updated_by", length = 200)
	public String getCtryUpdatedBy() {
		return this.ctryUpdatedBy;
	}

	public void setCtryUpdatedBy(String ctryUpdatedBy) {
		this.ctryUpdatedBy = ctryUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ctry_updated_on", length = 29)
	public Date getCtryUpdatedOn() {
		return this.ctryUpdatedOn;
	}

	public void setCtryUpdatedOn(Date ctryUpdatedOn) {
		this.ctryUpdatedOn = ctryUpdatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCountry")
	public Set<TState> getTStates() {
		return this.TStates;
	}

	public void setTStates(Set<TState> TStates) {
		this.TStates = TStates;
	}

}
