package com.otv.model;

// default package
// Generated Jun 4, 2013 7:53:45 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPlacedOrder generated by hbm2java
 */
@Entity
@Table(name = "t_placed_order", schema = "public")
public class TPlacedOrder implements java.io.Serializable {

	private int plorId;
	private TCode TCode;
	private TPurchaseOrder TPurchaseOrder;
	private TProduct TProduct;
	private Date plorInitDate;
	private String plorUpdatedBy;
	private Date plorUpdatedOn;
	private Set<TPlorRcorLink> TPlorRcorLinks = new HashSet<TPlorRcorLink>(0);
	private Set<TPlorRmatLink> TPlorRmatLinks = new HashSet<TPlorRmatLink>(0);

	public TPlacedOrder() {
	}

	public TPlacedOrder(int plorId) {
		this.plorId = plorId;
	}

	public TPlacedOrder(int plorId, TCode TCode, TPurchaseOrder TPurchaseOrder,
			TProduct TProduct, Date plorInitDate, String plorUpdatedBy,
			Date plorUpdatedOn, Set<TPlorRcorLink> TPlorRcorLinks,
			Set<TPlorRmatLink> TPlorRmatLinks) {
		this.plorId = plorId;
		this.TCode = TCode;
		this.TPurchaseOrder = TPurchaseOrder;
		this.TProduct = TProduct;
		this.plorInitDate = plorInitDate;
		this.plorUpdatedBy = plorUpdatedBy;
		this.plorUpdatedOn = plorUpdatedOn;
		this.TPlorRcorLinks = TPlorRcorLinks;
		this.TPlorRmatLinks = TPlorRmatLinks;
	}

	@Id
	@Column(name = "plor_id", unique = true, nullable = false)
	public int getPlorId() {
		return this.plorId;
	}

	public void setPlorId(int plorId) {
		this.plorId = plorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plor_status_code_id")
	public TCode getTCode() {
		return this.TCode;
	}

	public void setTCode(TCode TCode) {
		this.TCode = TCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plor_purchase_order_id")
	public TPurchaseOrder getTPurchaseOrder() {
		return this.TPurchaseOrder;
	}

	public void setTPurchaseOrder(TPurchaseOrder TPurchaseOrder) {
		this.TPurchaseOrder = TPurchaseOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plor_product_id")
	public TProduct getTProduct() {
		return this.TProduct;
	}

	public void setTProduct(TProduct TProduct) {
		this.TProduct = TProduct;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "plor_init_date", length = 29)
	public Date getPlorInitDate() {
		return this.plorInitDate;
	}

	public void setPlorInitDate(Date plorInitDate) {
		this.plorInitDate = plorInitDate;
	}

	@Column(name = "plor_updated_by", length = 200)
	public String getPlorUpdatedBy() {
		return this.plorUpdatedBy;
	}

	public void setPlorUpdatedBy(String plorUpdatedBy) {
		this.plorUpdatedBy = plorUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "plor_updated_on", length = 29)
	public Date getPlorUpdatedOn() {
		return this.plorUpdatedOn;
	}

	public void setPlorUpdatedOn(Date plorUpdatedOn) {
		this.plorUpdatedOn = plorUpdatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPlacedOrder")
	public Set<TPlorRcorLink> getTPlorRcorLinks() {
		return this.TPlorRcorLinks;
	}

	public void setTPlorRcorLinks(Set<TPlorRcorLink> TPlorRcorLinks) {
		this.TPlorRcorLinks = TPlorRcorLinks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPlacedOrder")
	public Set<TPlorRmatLink> getTPlorRmatLinks() {
		return this.TPlorRmatLinks;
	}

	public void setTPlorRmatLinks(Set<TPlorRmatLink> TPlorRmatLinks) {
		this.TPlorRmatLinks = TPlorRmatLinks;
	}

}
