package com.otv.model;

// default package
// Generated Jun 4, 2013 7:53:45 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPlorRcorLink generated by hbm2java
 */
@Entity
@Table(name = "t_plor_rcor_link", schema = "public")
public class TPlorRcorLink implements java.io.Serializable {

	private int plrcId;
	private TReceivedOrder TReceivedOrder;
	private TCode TCode;
	private TPlacedOrder TPlacedOrder;
	private String plrcUpdatedBy;
	private Date plrcUpdatedOn;

	public TPlorRcorLink() {
	}

	public TPlorRcorLink(int plrcId) {
		this.plrcId = plrcId;
	}

	public TPlorRcorLink(int plrcId, TReceivedOrder TReceivedOrder,
			TCode TCode, TPlacedOrder TPlacedOrder, String plrcUpdatedBy,
			Date plrcUpdatedOn) {
		this.plrcId = plrcId;
		this.TReceivedOrder = TReceivedOrder;
		this.TCode = TCode;
		this.TPlacedOrder = TPlacedOrder;
		this.plrcUpdatedBy = plrcUpdatedBy;
		this.plrcUpdatedOn = plrcUpdatedOn;
	}

	@Id
	@Column(name = "plrc_id", unique = true, nullable = false)
	public int getPlrcId() {
		return this.plrcId;
	}

	public void setPlrcId(int plrcId) {
		this.plrcId = plrcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plrc_received_order_id")
	public TReceivedOrder getTReceivedOrder() {
		return this.TReceivedOrder;
	}

	public void setTReceivedOrder(TReceivedOrder TReceivedOrder) {
		this.TReceivedOrder = TReceivedOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plrc_status_code_id")
	public TCode getTCode() {
		return this.TCode;
	}

	public void setTCode(TCode TCode) {
		this.TCode = TCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plrc_placed_order_id")
	public TPlacedOrder getTPlacedOrder() {
		return this.TPlacedOrder;
	}

	public void setTPlacedOrder(TPlacedOrder TPlacedOrder) {
		this.TPlacedOrder = TPlacedOrder;
	}

	@Column(name = "plrc_updated_by", length = 200)
	public String getPlrcUpdatedBy() {
		return this.plrcUpdatedBy;
	}

	public void setPlrcUpdatedBy(String plrcUpdatedBy) {
		this.plrcUpdatedBy = plrcUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "plrc_updated_on", length = 29)
	public Date getPlrcUpdatedOn() {
		return this.plrcUpdatedOn;
	}

	public void setPlrcUpdatedOn(Date plrcUpdatedOn) {
		this.plrcUpdatedOn = plrcUpdatedOn;
	}

}
