package com.otv.model;

// default package
// Generated Jun 4, 2013 7:53:45 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPlorRmatLink generated by hbm2java
 */
@Entity
@Table(name = "t_plor_rmat_link", schema = "public")
public class TPlorRmatLink implements java.io.Serializable {

	private int plrmId;
	private TCode TCodeByPlrmQuantityUnitCodeId;
	private TCode TCodeByPlrmWeightUnitCodeId;
	private TPlacedOrder TPlacedOrder;
	private TRawMaterial TRawMaterial;
	private BigDecimal plrmWeight;
	private BigDecimal plrmQuantity;
	private String plrmUpdatedBy;
	private Date plrmUpdatedOn;

	public TPlorRmatLink() {
	}

	public TPlorRmatLink(int plrmId) {
		this.plrmId = plrmId;
	}

	public TPlorRmatLink(int plrmId, TCode TCodeByPlrmQuantityUnitCodeId,
			TCode TCodeByPlrmWeightUnitCodeId, TPlacedOrder TPlacedOrder,
			TRawMaterial TRawMaterial, BigDecimal plrmWeight,
			BigDecimal plrmQuantity, String plrmUpdatedBy, Date plrmUpdatedOn) {
		this.plrmId = plrmId;
		this.TCodeByPlrmQuantityUnitCodeId = TCodeByPlrmQuantityUnitCodeId;
		this.TCodeByPlrmWeightUnitCodeId = TCodeByPlrmWeightUnitCodeId;
		this.TPlacedOrder = TPlacedOrder;
		this.TRawMaterial = TRawMaterial;
		this.plrmWeight = plrmWeight;
		this.plrmQuantity = plrmQuantity;
		this.plrmUpdatedBy = plrmUpdatedBy;
		this.plrmUpdatedOn = plrmUpdatedOn;
	}

	@Id
	@Column(name = "plrm_id", unique = true, nullable = false)
	public int getPlrmId() {
		return this.plrmId;
	}

	public void setPlrmId(int plrmId) {
		this.plrmId = plrmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plrm_quantity_unit_code_id")
	public TCode getTCodeByPlrmQuantityUnitCodeId() {
		return this.TCodeByPlrmQuantityUnitCodeId;
	}

	public void setTCodeByPlrmQuantityUnitCodeId(
			TCode TCodeByPlrmQuantityUnitCodeId) {
		this.TCodeByPlrmQuantityUnitCodeId = TCodeByPlrmQuantityUnitCodeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plrm_weight_unit_code_id")
	public TCode getTCodeByPlrmWeightUnitCodeId() {
		return this.TCodeByPlrmWeightUnitCodeId;
	}

	public void setTCodeByPlrmWeightUnitCodeId(TCode TCodeByPlrmWeightUnitCodeId) {
		this.TCodeByPlrmWeightUnitCodeId = TCodeByPlrmWeightUnitCodeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plrm_placed_order_id")
	public TPlacedOrder getTPlacedOrder() {
		return this.TPlacedOrder;
	}

	public void setTPlacedOrder(TPlacedOrder TPlacedOrder) {
		this.TPlacedOrder = TPlacedOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plrm_raw_material_id")
	public TRawMaterial getTRawMaterial() {
		return this.TRawMaterial;
	}

	public void setTRawMaterial(TRawMaterial TRawMaterial) {
		this.TRawMaterial = TRawMaterial;
	}

	@Column(name = "plrm_weight", precision = 10, scale = 4)
	public BigDecimal getPlrmWeight() {
		return this.plrmWeight;
	}

	public void setPlrmWeight(BigDecimal plrmWeight) {
		this.plrmWeight = plrmWeight;
	}

	@Column(name = "plrm_quantity", precision = 10, scale = 4)
	public BigDecimal getPlrmQuantity() {
		return this.plrmQuantity;
	}

	public void setPlrmQuantity(BigDecimal plrmQuantity) {
		this.plrmQuantity = plrmQuantity;
	}

	@Column(name = "plrm_updated_by", length = 200)
	public String getPlrmUpdatedBy() {
		return this.plrmUpdatedBy;
	}

	public void setPlrmUpdatedBy(String plrmUpdatedBy) {
		this.plrmUpdatedBy = plrmUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "plrm_updated_on", length = 29)
	public Date getPlrmUpdatedOn() {
		return this.plrmUpdatedOn;
	}

	public void setPlrmUpdatedOn(Date plrmUpdatedOn) {
		this.plrmUpdatedOn = plrmUpdatedOn;
	}

}
