package com.otv.model;

// default package
// Generated Jun 4, 2013 7:53:45 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TProperty generated by hbm2java
 */
@Entity
@Table(name = "t_property", schema = "public")
public class TProperty implements java.io.Serializable {

	private int prptId;
	private TCode TCodeByPrptPrimaryColorCodeId;
	private TCode TCodeByPrptThicknessUnitCodeId;
	private TCode TCodeByPrptLengthUnitCodeId;
	private TCode TCodeByPrptWidthUnitCodeId;
	private TCode TCodeByPrptHeightUnitCodeId;
	private Boolean prptPrimaryColAvlbl;
	private BigDecimal prptLength;
	private Boolean prptLengthAvlbl;
	private BigDecimal prptWidth;
	private Boolean prptWidthAvlbl;
	private BigDecimal prptHeight;
	private Boolean prptHeightAvlbl;
	private BigDecimal prptThickness;
	private Boolean prptThicknessAvlbl;
	private String prptUpdatedBy;
	private Date prptUpdatedOn;
	private Set<TRawMaterial> TRawMaterials = new HashSet<TRawMaterial>(0);

	public TProperty() {
	}

	public TProperty(int prptId) {
		this.prptId = prptId;
	}

	public TProperty(int prptId, TCode TCodeByPrptPrimaryColorCodeId,
			TCode TCodeByPrptThicknessUnitCodeId,
			TCode TCodeByPrptLengthUnitCodeId,
			TCode TCodeByPrptWidthUnitCodeId,
			TCode TCodeByPrptHeightUnitCodeId, Boolean prptPrimaryColAvlbl,
			BigDecimal prptLength, Boolean prptLengthAvlbl,
			BigDecimal prptWidth, Boolean prptWidthAvlbl,
			BigDecimal prptHeight, Boolean prptHeightAvlbl,
			BigDecimal prptThickness, Boolean prptThicknessAvlbl,
			String prptUpdatedBy, Date prptUpdatedOn,
			Set<TRawMaterial> TRawMaterials) {
		this.prptId = prptId;
		this.TCodeByPrptPrimaryColorCodeId = TCodeByPrptPrimaryColorCodeId;
		this.TCodeByPrptThicknessUnitCodeId = TCodeByPrptThicknessUnitCodeId;
		this.TCodeByPrptLengthUnitCodeId = TCodeByPrptLengthUnitCodeId;
		this.TCodeByPrptWidthUnitCodeId = TCodeByPrptWidthUnitCodeId;
		this.TCodeByPrptHeightUnitCodeId = TCodeByPrptHeightUnitCodeId;
		this.prptPrimaryColAvlbl = prptPrimaryColAvlbl;
		this.prptLength = prptLength;
		this.prptLengthAvlbl = prptLengthAvlbl;
		this.prptWidth = prptWidth;
		this.prptWidthAvlbl = prptWidthAvlbl;
		this.prptHeight = prptHeight;
		this.prptHeightAvlbl = prptHeightAvlbl;
		this.prptThickness = prptThickness;
		this.prptThicknessAvlbl = prptThicknessAvlbl;
		this.prptUpdatedBy = prptUpdatedBy;
		this.prptUpdatedOn = prptUpdatedOn;
		this.TRawMaterials = TRawMaterials;
	}

	@Id
	@Column(name = "prpt_id", unique = true, nullable = false)
	public int getPrptId() {
		return this.prptId;
	}

	public void setPrptId(int prptId) {
		this.prptId = prptId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prpt_primary_color_code_id")
	public TCode getTCodeByPrptPrimaryColorCodeId() {
		return this.TCodeByPrptPrimaryColorCodeId;
	}

	public void setTCodeByPrptPrimaryColorCodeId(
			TCode TCodeByPrptPrimaryColorCodeId) {
		this.TCodeByPrptPrimaryColorCodeId = TCodeByPrptPrimaryColorCodeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prpt_thickness_unit_code_id")
	public TCode getTCodeByPrptThicknessUnitCodeId() {
		return this.TCodeByPrptThicknessUnitCodeId;
	}

	public void setTCodeByPrptThicknessUnitCodeId(
			TCode TCodeByPrptThicknessUnitCodeId) {
		this.TCodeByPrptThicknessUnitCodeId = TCodeByPrptThicknessUnitCodeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prpt_length_unit_code_id")
	public TCode getTCodeByPrptLengthUnitCodeId() {
		return this.TCodeByPrptLengthUnitCodeId;
	}

	public void setTCodeByPrptLengthUnitCodeId(TCode TCodeByPrptLengthUnitCodeId) {
		this.TCodeByPrptLengthUnitCodeId = TCodeByPrptLengthUnitCodeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prpt_width_unit_code_id")
	public TCode getTCodeByPrptWidthUnitCodeId() {
		return this.TCodeByPrptWidthUnitCodeId;
	}

	public void setTCodeByPrptWidthUnitCodeId(TCode TCodeByPrptWidthUnitCodeId) {
		this.TCodeByPrptWidthUnitCodeId = TCodeByPrptWidthUnitCodeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prpt_height_unit_code_id")
	public TCode getTCodeByPrptHeightUnitCodeId() {
		return this.TCodeByPrptHeightUnitCodeId;
	}

	public void setTCodeByPrptHeightUnitCodeId(TCode TCodeByPrptHeightUnitCodeId) {
		this.TCodeByPrptHeightUnitCodeId = TCodeByPrptHeightUnitCodeId;
	}

	@Column(name = "prpt_primary_col_avlbl")
	public Boolean getPrptPrimaryColAvlbl() {
		return this.prptPrimaryColAvlbl;
	}

	public void setPrptPrimaryColAvlbl(Boolean prptPrimaryColAvlbl) {
		this.prptPrimaryColAvlbl = prptPrimaryColAvlbl;
	}

	@Column(name = "prpt_length", precision = 10, scale = 4)
	public BigDecimal getPrptLength() {
		return this.prptLength;
	}

	public void setPrptLength(BigDecimal prptLength) {
		this.prptLength = prptLength;
	}

	@Column(name = "prpt_length_avlbl")
	public Boolean getPrptLengthAvlbl() {
		return this.prptLengthAvlbl;
	}

	public void setPrptLengthAvlbl(Boolean prptLengthAvlbl) {
		this.prptLengthAvlbl = prptLengthAvlbl;
	}

	@Column(name = "prpt_width", precision = 10, scale = 4)
	public BigDecimal getPrptWidth() {
		return this.prptWidth;
	}

	public void setPrptWidth(BigDecimal prptWidth) {
		this.prptWidth = prptWidth;
	}

	@Column(name = "prpt_width_avlbl")
	public Boolean getPrptWidthAvlbl() {
		return this.prptWidthAvlbl;
	}

	public void setPrptWidthAvlbl(Boolean prptWidthAvlbl) {
		this.prptWidthAvlbl = prptWidthAvlbl;
	}

	@Column(name = "prpt_height", precision = 10, scale = 4)
	public BigDecimal getPrptHeight() {
		return this.prptHeight;
	}

	public void setPrptHeight(BigDecimal prptHeight) {
		this.prptHeight = prptHeight;
	}

	@Column(name = "prpt_height_avlbl")
	public Boolean getPrptHeightAvlbl() {
		return this.prptHeightAvlbl;
	}

	public void setPrptHeightAvlbl(Boolean prptHeightAvlbl) {
		this.prptHeightAvlbl = prptHeightAvlbl;
	}

	@Column(name = "prpt_thickness", precision = 10, scale = 4)
	public BigDecimal getPrptThickness() {
		return this.prptThickness;
	}

	public void setPrptThickness(BigDecimal prptThickness) {
		this.prptThickness = prptThickness;
	}

	@Column(name = "prpt_thickness_avlbl")
	public Boolean getPrptThicknessAvlbl() {
		return this.prptThicknessAvlbl;
	}

	public void setPrptThicknessAvlbl(Boolean prptThicknessAvlbl) {
		this.prptThicknessAvlbl = prptThicknessAvlbl;
	}

	@Column(name = "prpt_updated_by", length = 200)
	public String getPrptUpdatedBy() {
		return this.prptUpdatedBy;
	}

	public void setPrptUpdatedBy(String prptUpdatedBy) {
		this.prptUpdatedBy = prptUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "prpt_updated_on", length = 29)
	public Date getPrptUpdatedOn() {
		return this.prptUpdatedOn;
	}

	public void setPrptUpdatedOn(Date prptUpdatedOn) {
		this.prptUpdatedOn = prptUpdatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TProperty")
	public Set<TRawMaterial> getTRawMaterials() {
		return this.TRawMaterials;
	}

	public void setTRawMaterials(Set<TRawMaterial> TRawMaterials) {
		this.TRawMaterials = TRawMaterials;
	}

}
