package com.otv.model;

// default package
// Generated Jun 4, 2013 7:53:45 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TProduct generated by hbm2java
 */
@Entity
@Table(name = "t_product", schema = "public")
public class TProduct implements java.io.Serializable {

	private int prodId;
	private TCode TCodeByProdNameCodeId;
	private TCode TCodeByProdTypeCodeId;
	private Boolean prodIsSample;
	private String prodUpdatedBy;
	private Date prodUpdatedOn;
	private Set<TPlacedOrder> TPlacedOrders = new HashSet<TPlacedOrder>(0);

	public TProduct() {
	}

	public TProduct(int prodId) {
		this.prodId = prodId;
	}

	public TProduct(int prodId, TCode TCodeByProdNameCodeId,
			TCode TCodeByProdTypeCodeId, Boolean prodIsSample,
			String prodUpdatedBy, Date prodUpdatedOn,
			Set<TPlacedOrder> TPlacedOrders) {
		this.prodId = prodId;
		this.TCodeByProdNameCodeId = TCodeByProdNameCodeId;
		this.TCodeByProdTypeCodeId = TCodeByProdTypeCodeId;
		this.prodIsSample = prodIsSample;
		this.prodUpdatedBy = prodUpdatedBy;
		this.prodUpdatedOn = prodUpdatedOn;
		this.TPlacedOrders = TPlacedOrders;
	}

	@Id
	@Column(name = "prod_id", unique = true, nullable = false)
	public int getProdId() {
		return this.prodId;
	}

	public void setProdId(int prodId) {
		this.prodId = prodId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prod_name_code_id")
	public TCode getTCodeByProdNameCodeId() {
		return this.TCodeByProdNameCodeId;
	}

	public void setTCodeByProdNameCodeId(TCode TCodeByProdNameCodeId) {
		this.TCodeByProdNameCodeId = TCodeByProdNameCodeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prod_type_code_id")
	public TCode getTCodeByProdTypeCodeId() {
		return this.TCodeByProdTypeCodeId;
	}

	public void setTCodeByProdTypeCodeId(TCode TCodeByProdTypeCodeId) {
		this.TCodeByProdTypeCodeId = TCodeByProdTypeCodeId;
	}

	@Column(name = "prod_is_sample")
	public Boolean getProdIsSample() {
		return this.prodIsSample;
	}

	public void setProdIsSample(Boolean prodIsSample) {
		this.prodIsSample = prodIsSample;
	}

	@Column(name = "prod_updated_by", length = 200)
	public String getProdUpdatedBy() {
		return this.prodUpdatedBy;
	}

	public void setProdUpdatedBy(String prodUpdatedBy) {
		this.prodUpdatedBy = prodUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "prod_updated_on", length = 29)
	public Date getProdUpdatedOn() {
		return this.prodUpdatedOn;
	}

	public void setProdUpdatedOn(Date prodUpdatedOn) {
		this.prodUpdatedOn = prodUpdatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TProduct")
	public Set<TPlacedOrder> getTPlacedOrders() {
		return this.TPlacedOrders;
	}

	public void setTPlacedOrders(Set<TPlacedOrder> TPlacedOrders) {
		this.TPlacedOrders = TPlacedOrders;
	}

}
