package com.otv.model;

// default package
// Generated Jun 4, 2013 7:53:45 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPurchaseOrder generated by hbm2java
 */
@Entity
@Table(name = "t_purchase_order", schema = "public")
public class TPurchaseOrder implements java.io.Serializable {

	private int puorId;
	private TCode TCode;
	private TActor TActorByPuorClientId;
	private TActor TActorByPuorVendorId;
	private Date puorInitDate;
	private String puorUpdatedBy;
	private Date puorUpdatedOn;
	private Set<TPlacedOrder> TPlacedOrders = new HashSet<TPlacedOrder>(0);

	public TPurchaseOrder() {
	}

	public TPurchaseOrder(int puorId) {
		this.puorId = puorId;
	}

	public TPurchaseOrder(int puorId, TCode TCode, TActor TActorByPuorClientId,
			TActor TActorByPuorVendorId, Date puorInitDate,
			String puorUpdatedBy, Date puorUpdatedOn,
			Set<TPlacedOrder> TPlacedOrders) {
		this.puorId = puorId;
		this.TCode = TCode;
		this.TActorByPuorClientId = TActorByPuorClientId;
		this.TActorByPuorVendorId = TActorByPuorVendorId;
		this.puorInitDate = puorInitDate;
		this.puorUpdatedBy = puorUpdatedBy;
		this.puorUpdatedOn = puorUpdatedOn;
		this.TPlacedOrders = TPlacedOrders;
	}

	@Id
	@Column(name = "puor_id", unique = true, nullable = false)
	public int getPuorId() {
		return this.puorId;
	}

	public void setPuorId(int puorId) {
		this.puorId = puorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "puor_status_code_id")
	public TCode getTCode() {
		return this.TCode;
	}

	public void setTCode(TCode TCode) {
		this.TCode = TCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "puor_client_id")
	public TActor getTActorByPuorClientId() {
		return this.TActorByPuorClientId;
	}

	public void setTActorByPuorClientId(TActor TActorByPuorClientId) {
		this.TActorByPuorClientId = TActorByPuorClientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "puor_vendor_id")
	public TActor getTActorByPuorVendorId() {
		return this.TActorByPuorVendorId;
	}

	public void setTActorByPuorVendorId(TActor TActorByPuorVendorId) {
		this.TActorByPuorVendorId = TActorByPuorVendorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "puor_init_date", length = 29)
	public Date getPuorInitDate() {
		return this.puorInitDate;
	}

	public void setPuorInitDate(Date puorInitDate) {
		this.puorInitDate = puorInitDate;
	}

	@Column(name = "puor_updated_by", length = 200)
	public String getPuorUpdatedBy() {
		return this.puorUpdatedBy;
	}

	public void setPuorUpdatedBy(String puorUpdatedBy) {
		this.puorUpdatedBy = puorUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "puor_updated_on", length = 29)
	public Date getPuorUpdatedOn() {
		return this.puorUpdatedOn;
	}

	public void setPuorUpdatedOn(Date puorUpdatedOn) {
		this.puorUpdatedOn = puorUpdatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPurchaseOrder")
	public Set<TPlacedOrder> getTPlacedOrders() {
		return this.TPlacedOrders;
	}

	public void setTPlacedOrders(Set<TPlacedOrder> TPlacedOrders) {
		this.TPlacedOrders = TPlacedOrders;
	}

}
