package com.otv.model;

// default package
// Generated Jun 4, 2013 7:53:45 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TReceivedOrder generated by hbm2java
 */
@Entity
@Table(name = "t_received_order", schema = "public")
public class TReceivedOrder implements java.io.Serializable {

	private int rcorId;
	private TCode TCode;
	private Date rcorInitDate;
	private String rcorUpdatedBy;
	private Date rcorUpdatedOn;
	private Set<TRcorRmatLink> TRcorRmatLinks = new HashSet<TRcorRmatLink>(0);
	private Set<TPlorRcorLink> TPlorRcorLinks = new HashSet<TPlorRcorLink>(0);

	public TReceivedOrder() {
	}

	public TReceivedOrder(int rcorId) {
		this.rcorId = rcorId;
	}

	public TReceivedOrder(int rcorId, TCode TCode, Date rcorInitDate,
			String rcorUpdatedBy, Date rcorUpdatedOn,
			Set<TRcorRmatLink> TRcorRmatLinks, Set<TPlorRcorLink> TPlorRcorLinks) {
		this.rcorId = rcorId;
		this.TCode = TCode;
		this.rcorInitDate = rcorInitDate;
		this.rcorUpdatedBy = rcorUpdatedBy;
		this.rcorUpdatedOn = rcorUpdatedOn;
		this.TRcorRmatLinks = TRcorRmatLinks;
		this.TPlorRcorLinks = TPlorRcorLinks;
	}

	@Id
	@Column(name = "rcor_id", unique = true, nullable = false)
	public int getRcorId() {
		return this.rcorId;
	}

	public void setRcorId(int rcorId) {
		this.rcorId = rcorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rcor_status_code_id")
	public TCode getTCode() {
		return this.TCode;
	}

	public void setTCode(TCode TCode) {
		this.TCode = TCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rcor_init_date", length = 29)
	public Date getRcorInitDate() {
		return this.rcorInitDate;
	}

	public void setRcorInitDate(Date rcorInitDate) {
		this.rcorInitDate = rcorInitDate;
	}

	@Column(name = "rcor_updated_by", length = 200)
	public String getRcorUpdatedBy() {
		return this.rcorUpdatedBy;
	}

	public void setRcorUpdatedBy(String rcorUpdatedBy) {
		this.rcorUpdatedBy = rcorUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rcor_updated_on", length = 29)
	public Date getRcorUpdatedOn() {
		return this.rcorUpdatedOn;
	}

	public void setRcorUpdatedOn(Date rcorUpdatedOn) {
		this.rcorUpdatedOn = rcorUpdatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TReceivedOrder")
	public Set<TRcorRmatLink> getTRcorRmatLinks() {
		return this.TRcorRmatLinks;
	}

	public void setTRcorRmatLinks(Set<TRcorRmatLink> TRcorRmatLinks) {
		this.TRcorRmatLinks = TRcorRmatLinks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TReceivedOrder")
	public Set<TPlorRcorLink> getTPlorRcorLinks() {
		return this.TPlorRcorLinks;
	}

	public void setTPlorRcorLinks(Set<TPlorRcorLink> TPlorRcorLinks) {
		this.TPlorRcorLinks = TPlorRcorLinks;
	}

}
