package com.otv.model;

// default package
// Generated Jun 4, 2013 7:53:45 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TState generated by hbm2java
 */
@Entity
@Table(name = "t_state", schema = "public")
public class TState implements java.io.Serializable {

	private int statId;
	private TCountry TCountry;
	private TCode TCode;
	private String statUpdatedBy;
	private Date statUpdatedOn;
	private Set<TCity> TCities = new HashSet<TCity>(0);

	public TState() {
	}

	public TState(int statId) {
		this.statId = statId;
	}

	public TState(int statId, TCountry TCountry, TCode TCode,
			String statUpdatedBy, Date statUpdatedOn, Set<TCity> TCities) {
		this.statId = statId;
		this.TCountry = TCountry;
		this.TCode = TCode;
		this.statUpdatedBy = statUpdatedBy;
		this.statUpdatedOn = statUpdatedOn;
		this.TCities = TCities;
	}

	@Id
	@Column(name = "stat_id", unique = true, nullable = false)
	public int getStatId() {
		return this.statId;
	}

	public void setStatId(int statId) {
		this.statId = statId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stat_country_id")
	public TCountry getTCountry() {
		return this.TCountry;
	}

	public void setTCountry(TCountry TCountry) {
		this.TCountry = TCountry;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stat_code_id")
	public TCode getTCode() {
		return this.TCode;
	}

	public void setTCode(TCode TCode) {
		this.TCode = TCode;
	}

	@Column(name = "stat_updated_by", length = 200)
	public String getStatUpdatedBy() {
		return this.statUpdatedBy;
	}

	public void setStatUpdatedBy(String statUpdatedBy) {
		this.statUpdatedBy = statUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "stat_updated_on", length = 29)
	public Date getStatUpdatedOn() {
		return this.statUpdatedOn;
	}

	public void setStatUpdatedOn(Date statUpdatedOn) {
		this.statUpdatedOn = statUpdatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TState")
	public Set<TCity> getTCities() {
		return this.TCities;
	}

	public void setTCities(Set<TCity> TCities) {
		this.TCities = TCities;
	}

}
